description: >
  yarn run build

executor:
  name: default
  tag: << parameters.node_version >>

parameters:
  attach_at:
    description: where should we attach the workspace
    default: "."
    type: string
  cdk_directory:
    description: the directory where your cdk app resides
    type: string
    default: "."
  yarn_params:
    description: the parameters to pass the `yarn run build` command
    type: string
    default: ""
  node_version:
    description: the version of node to use in executor
    type: string
    default: "18.13.0"
  environment:
    default: ENVIRONMENT
    description: The environment to apply on.
    type: env_var_name

steps:
  - esbuild
  - yarn:
      yarn_command: run
      yarn_params: build << parameters.yarn_params >>
      yarn_directory: << parameters.cdk_directory >>
      attach_at: << parameters.attach_at >>
      persist: true
