description: >
  yarn run build

executor: default

parameters:
  cdk_directory:
    description: the directory where your cdk app resides
    type: string
    default: "."
  yarn_params:
    description: the parameters to pass the `yarn run build` command
    type: string
    default: ""

steps:
  - node/install-yarn:
      version: "1.22.17"
  - esbuild
  - yarn:
      yarn_command: run
      yarn_params: build << parameters.yarn_params >>
      yarn_directory: << parameters.cdk_directory >>
      persist: true
